apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    app: ${DEPLOYMENT_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${APP_PORT}
  type: NodePort
